import assert from 'node:assert/strict';
import { randomUUID,randomBytes,createHmac } from 'node:crypto';
import argon2 from 'argon2';
import { buildApp } from '../app.js';
import { getEnv } from '../config/env.js';
import { loadLocalEnv } from '../config/load-env.js';
import { createPool } from '../database/pool.js';
import { createTokenPair } from '../modules/auth/token.service.js';
import { rollbackDatabase } from './rollback-database.js';
import { IfoodIntegrationService } from '../integrations/ifood/ifood.integration.js';
import { createIfoodProvider } from '../integrations/ifood/ifood.module.js';
import { mockOrder } from '../integrations/ifood/ifood.mock.js';
import { IfoodHttpError } from '../integrations/ifood/ifood.client.js';
import type { ExternalOrderProvider } from '../integrations/external-orders/external-order-provider.js';
import { io } from 'socket.io-client';

loadLocalEnv();const source=getEnv();if(source.NODE_ENV==='production')throw Error('Development only');
const ui=process.argv.includes('--ui'),password='Synthetic-ifood-9821!';
const env={...source,NODE_ENV:ui?'development' as const:'test' as const,LOG_LEVEL:'error' as const,IFOOD_ENABLED:true,IFOOD_MODE:'mock' as const,
  IFOOD_EVENTS_MODE:'polling' as const,REDIS_URL:'',REDIS_REQUIRED:false,APP_ORIGINS:source.APP_ORIGINS+',http://localhost:8101'};
const pool=createPool(env),connection=await pool.connect();await connection.query('BEGIN');
const db=rollbackDatabase(pool,connection),prefix='ifood-'+randomBytes(5).toString('hex');let app:Awaited<ReturnType<typeof buildApp>>|undefined;let checks=0;
const check=(v:unknown,label:string)=>{assert.ok(v,label);checks++;};
try{
 const master=randomUUID(),tenant=randomUUID(),company=randomUUID(),store=randomUUID(),sibling=randomUUID(),user=randomUUID(),driverUser=randomUUID(),driverId=randomUUID(),merchant=randomUUID();
 await db.query(`INSERT INTO platform_admins(id,name,email,password_hash) VALUES($1,'Synthetic master',$2,'not-a-password')`,[master,prefix+'-master@example.test']);
 await db.query("SELECT set_config('app.platform_admin_id',$1,true)",[master]);
 await db.query(`INSERT INTO tenants(id,name,slug) VALUES($1,'Synthetic iFood',$2)`,[tenant,prefix]);
 await db.query(`INSERT INTO companies(id,tenant_id,name,legal_name) VALUES($1,$2,'Synthetic company','Synthetic company')`,[company,tenant]);
 for(const id of [store,sibling])await db.query(`INSERT INTO stores(id,tenant_id,company_id,name,address_line,city,state,latitude,longitude) VALUES($1,$2,$3,'Synthetic unit','Avenida Brasil','Uberlandia','MG',-18.9,-48.2)`,[id,tenant,company]);
 for(const [id,label]of [[user,'manager'],[driverUser,'driver']])await db.query(`INSERT INTO users(id,name,email,password_hash,email_verified_at) VALUES($1,$2,$3,$4,now())`,[id,'Synthetic '+label,prefix+'-'+label+'@example.test',ui?await argon2.hash(password):'not-a-password']);
 await db.query(`INSERT INTO tenant_users(tenant_id,user_id,role) VALUES($1,$2,'TENANT_MANAGER'),($1,$3,'COURIER')`,[tenant,user,driverUser]);
 await db.query(`INSERT INTO user_access_scopes(tenant_id,user_id,scope_level) VALUES($1,$2,'TENANT')`,[tenant,user]);
 await db.query(`INSERT INTO courier_profiles(id,user_id,phone,vehicle_type,status) VALUES($1,$2,'34999990000','MOTORCYCLE','ACTIVE')`,[driverId,driverUser]);
 await db.query(`INSERT INTO courier_store_links(tenant_id,store_id,courier_profile_id,status) VALUES($1,$2,$3,'ACTIVE')`,[tenant,store,driverId]);
 await db.query("SELECT set_config('app.platform_admin_id','',true)");
 const token=async(id:string,storeId:string,role:'TENANT_MANAGER'|'COURIER')=>(await createTokenPair(env,{userId:id,tenantId:tenant,storeIds:[storeId],role})).accessToken;
 const manager=await token(user,store,'TENANT_MANAGER'),other=await token(user,sibling,'TENANT_MANAGER'),courier=await token(driverUser,store,'COURIER');
 app=await buildApp({env,database:db});await app.listen({host:'127.0.0.1',port:ui?3000:0});
 const address=app.server.address();assert.ok(address&&typeof address!=='string');
 const scopedSocket=io(`http://127.0.0.1:${address.port}/operations`,{auth:{accessToken:manager},transports:['websocket'],reconnection:false});
 const siblingSocket=io(`http://127.0.0.1:${address.port}/operations`,{auth:{accessToken:other},transports:['websocket'],reconnection:false});
 const connected=(socket:typeof scopedSocket)=>new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Socket connect timeout')),5000);socket.once('connect',()=>{clearTimeout(timeout);resolve();});socket.once('connect_error',e=>{clearTimeout(timeout);reject(e);});});
 try{
   await Promise.all([connected(scopedSocket),connected(siblingSocket)]);let siblingReceived=false;siblingSocket.on('operation:changed',()=>{siblingReceived=true;});
   const changed=new Promise<unknown>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Integration realtime timeout')),5000);scopedSocket.once('operation:changed',payload=>{clearTimeout(timeout);resolve(payload);});});
   await pool.query("SELECT pg_notify('rastreia_operation_changed',$1)",[JSON.stringify({tenantId:tenant,storeId:store})]);
   assert.deepEqual(await changed,{storeId:store});checks++;await new Promise(resolve=>setTimeout(resolve,150));check(!siblingReceived,'Integration realtime isolates sibling stores and carries no customer data');
 }finally{scopedSocket.disconnect();siblingSocket.disconnect();}
 const call=async(method:'GET'|'POST'|'PUT',url:string,payload?:object,bearer=manager)=>{const r=await app!.inject({method,url,...(payload?{payload}:{}),headers:{authorization:'Bearer '+bearer,'idempotency-key':randomUUID()}});return {status:r.statusCode,body:r.json()};};
 const configured=await call('PUT','/integrations/ifood/connection',{storeId:store,merchantId:merchant,enabled:true,autoImportOrders:true,autoCreateDelivery:true,deliveryDispatchMode:'IMMEDIATE',deliveryDispatchMinutesBefore:15});
 assert.equal(configured.status,200,JSON.stringify(configured.body));checks++;const integration=configured.body.id;
 check((await call('GET','/integrations/ifood',undefined,courier)).status===403,'Couriers cannot configure integrations');
 check((await call('GET','/integrations/ifood',undefined,other)).body.data.length===0,'RLS isolates sibling units');
 check((await call('POST',`/integrations/ifood/${integration}/test`)).status===200,'Mock connection test works');
 const provider=createIfoodProvider(db,env),service=new IfoodIntegrationService(db,env,provider);
 const overridden=(values:Partial<ExternalOrderProvider>)=>new Proxy(provider,{get(target,key){const value:unknown=values[key as keyof ExternalOrderProvider]??Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});
 const eventFor=(raw:ReturnType<typeof mockOrder>,code='PLC',fullCode='PLACED')=>({id:'mock-'+randomUUID(),merchantId:merchant,orderId:raw.id,code,fullCode,createdAt:new Date().toISOString(),mockOrder:raw});
 const raw=mockOrder('cash',merchant),event=eventFor(raw);await service.ingest(event);await service.ingest(event);await service.ingest({...event,id:'mock-'+randomUUID()});
 await service.processEvents();
 const errors=(await db.query(`SELECT last_error FROM integration_events WHERE integration_id=$1 AND status='ERROR'`,[integration])).rows;
 assert.deepEqual(errors,[],'Import errors: '+JSON.stringify(errors));checks++;
 const orders=(await call('GET','/external-orders')).body.data;check(orders.length===1,'Duplicate events/order create one external order');const id=orders[0].id,deliveryId=orders[0].delivery_id;
 check((await db.query('SELECT count(*)::int AS n FROM deliveries WHERE external_order_id=$1',[id])).rows[0].n===1,'Exactly one delivery for duplicated order');
 check((await call('GET',`/deliveries/${deliveryId}`)).body.status==='DRAFT','Delivery held until external confirmation');
 check((await db.query("SELECT 1 FROM outbox_events WHERE aggregate_id=$1 AND event_type='delivery.created'",[deliveryId])).rowCount===0,'Draft does not publish delivery notifications before release');
 check((await call('GET',`/external-orders/${id}`,undefined,other)).status===404,'Other unit cannot read normalized customer details');
 const detail=(await call('GET',`/external-orders/${id}`)).body;check(detail.order.payments[0].cashChangeForCents===10000&&!('payload_encrypted' in detail),'Normalized payment and no raw payload exposed');
 check((await call('POST',`/external-orders/${id}/actions`,{action:'RELEASE_DELIVERY'})).status===409,'Cannot release unconfirmed order');
 check((await call('POST',`/external-orders/${id}/actions`,{action:'CONFIRM'})).status===200,'Manager can request confirmation');
 await call('POST',`/external-orders/${id}/actions`,{action:'CONFIRM'});await service.processCommands();
 check((await db.query('SELECT external_status FROM external_orders WHERE id=$1',[id])).rows[0].external_status==='PLACED','HTTP acceptance does not imply confirmation');
 check((await db.query("SELECT count(*)::int AS n FROM integration_commands WHERE external_order_id=$1 AND operation='CONFIRM'",[id])).rows[0].n===1,'Confirmation command deduplicated');
 await service.processEvents();await service.releaseDue();check((await call('GET',`/deliveries/${deliveryId}`)).body.status==='AWAITING_COURIER','Confirmation releases normal courier queue');
 await call('POST',`/external-orders/${id}/actions`,{action:'PREPARE'});await service.processCommands();await service.processEvents();
 const assigned=await call('POST',`/deliveries/${deliveryId}/assign`,{courierId:driverId});assert.equal(assigned.status,200,JSON.stringify(assigned.body));checks++;
 check((await db.query("SELECT 1 FROM integration_commands WHERE external_order_id=$1 AND operation='DISPATCH'",[id])).rowCount===0,'Accept/assignment does not dispatch iFood');
 check((await call('POST',`/deliveries/${deliveryId}/collect`,{},courier)).status===200,'Normal courier collection');
 check((await db.query("SELECT 1 FROM integration_commands WHERE external_order_id=$1 AND operation='DISPATCH'",[id])).rowCount===0,'Collection alone does not dispatch');
 check((await call('POST',`/deliveries/${deliveryId}/start`,{},courier)).status===200,'Normal route start');
 await service.processCommands();await service.processCommands();
 const dispatch=(await db.query("SELECT attempts,status FROM integration_commands WHERE external_order_id=$1 AND operation='DISPATCH'",[id])).rows;
 check(dispatch.length===1&&dispatch[0].attempts===1&&dispatch[0].status==='REQUEST_SENT','Dispatch sent once and waits event');await service.processEvents();
 check((await call('POST',`/deliveries/${deliveryId}/complete`,{},courier)).status===200,'Internal completion independent of external conclusion');
 check((await db.query('SELECT external_status FROM external_orders WHERE id=$1',[id])).rows[0].external_status==='DISPATCHED','Internal/external status remain separate');
 const outsourced=mockOrder('ifood',merchant);await service.ingest(eventFor(outsourced));await service.processEvents();
 check((await db.query('SELECT delivery_id,own_delivery FROM external_orders WHERE external_order_id=$1',[outsourced.id])).rows[0].delivery_id===null,'IFOOD logistics never creates delivery');
 const cancelRaw=mockOrder('own',merchant);await service.ingest(eventFor(cancelRaw));await service.processEvents();
 const cancelled=(await db.query('SELECT id,delivery_id FROM external_orders WHERE external_order_id=$1',[cancelRaw.id])).rows[0];
 check((await call('GET',`/external-orders/${cancelled.id}/cancellation-reasons`)).body.data.length===1,'Cancellation reasons provider');
 check((await call('POST',`/external-orders/${cancelled.id}/actions`,{action:'CANCEL',cancellationCode:'invalid'})).status===409,'Invalid cancellation reason rejected');
 await call('POST',`/external-orders/${cancelled.id}/actions`,{action:'CANCEL',cancellationCode:'501'});await service.processCommands();await service.processEvents();
 check((await call('GET',`/deliveries/${cancelled.delivery_id}`)).body.status==='CANCELLED','Confirmed external cancellation closes open delivery');
 await service.ingest(eventFor(cancelRaw));await service.processEvents();
 check((await db.query('SELECT external_status FROM external_orders WHERE id=$1',[cancelled.id])).rows[0].external_status==='CANCELLED','Late PLACED cannot resurrect cancelled order');
 await service.ingest(eventFor(raw,'UNKNOWN','UNKNOWN_EVENT'));await service.processEvents();
 check((await db.query("SELECT 1 FROM integration_events WHERE integration_id=$1 AND event_code='UNKNOWN' AND status='IGNORED'",[integration])).rowCount===1,'Unknown events persisted and ignored without stopping others');
 check((await call('POST','/integrations/ifood/webhook',event)).status===404,'Disabled webhook never processes payload');
 check((await call('GET',`/external-orders/${id}`,undefined,courier)).status===403,'Courier cannot read commercial order payload');
 const failedRaw=mockOrder('own',merchant),failedEvent=eventFor(failedRaw);await service.ingest(failedEvent);
 const failedService=new IfoodIntegrationService(db,env,overridden({getOrder:async()=>{throw new IfoodHttpError(404);}}));
 await failedService.processEvents();await failedService.processEvents();
 const failed=(await db.query('SELECT id,status,attempts,next_attempt_at>now() AS delayed FROM integration_events WHERE external_event_id=$1',[failedEvent.id])).rows[0];
 check(failed.status==='ERROR'&&failed.attempts===1&&failed.delayed,'404 is recorded with backoff and not retried immediately');
 check((await call('POST',`/integrations/ifood/events/${failed.id}/reprocess`)).status===200,'Manager can requeue a failed event');
 await service.processEvents();
 check((await db.query('SELECT 1 FROM external_orders WHERE external_order_id=$1',[failedRaw.id])).rowCount===1,'Reprocessed event creates a single delivery');
 const invalidRaw=mockOrder('own',merchant);delete (invalidRaw.delivery.deliveryAddress as Partial<typeof invalidRaw.delivery.deliveryAddress>).coordinates;
 const invalidEvent=eventFor(invalidRaw);await service.ingest(invalidEvent);await service.processEvents();
 check((await db.query("SELECT order_payload_encrypted IS NOT NULL AS preserved FROM integration_events WHERE external_event_id=$1 AND status='ERROR'",[invalidEvent.id])).rows[0]?.preserved,'Invalid destination retains encrypted details for investigation');
 for(let n=0;n<5;n++){await db.query('UPDATE integration_events SET next_attempt_at=now() WHERE external_event_id=$1',[invalidEvent.id]);await service.processEvents();}
 check((await db.query('SELECT attempts FROM integration_events WHERE external_event_id=$1',[invalidEvent.id])).rows[0].attempts===5,'Invalid orders stop after five attempts');
 await db.query('UPDATE integration_connections SET auto_create_delivery=false WHERE id=$1',[integration]);
 const manualRaw=mockOrder('own',merchant);await service.ingest(eventFor(manualRaw));await service.processEvents();
 const manual=(await db.query('SELECT id,delivery_id FROM external_orders WHERE external_order_id=$1',[manualRaw.id])).rows[0];
 check(manual.delivery_id===null,'Automatic creation can be disabled independently of import');
 const manualCreated=await call('POST',`/external-orders/${manual.id}/actions`,{action:'CREATE_DELIVERY'});
 check(manualCreated.status===200,'Manual creation uses the same delivery service');
 check((await call('POST',`/external-orders/${manual.id}/actions`,{action:'CREATE_DELIVERY'})).body.deliveryId===manualCreated.body.deliveryId,'Manual creation is idempotent');
 await call('POST',`/external-orders/${manual.id}/actions`,{action:'CONFIRM'});
 const throttled=new IfoodIntegrationService(db,env,overridden({confirmOrder:async()=>{throw new IfoodHttpError(429,120);}}));
 await throttled.processCommands();await throttled.processCommands();
 const throttledCmd=(await db.query("SELECT id,status,attempts,next_attempt_at>now()+interval '119 seconds' AS delayed FROM integration_commands WHERE external_order_id=$1 AND operation='CONFIRM'",[manual.id])).rows[0];
 check(throttledCmd.status==='REQUESTED'&&throttledCmd.attempts===1&&throttledCmd.delayed,'429 honors Retry-After without repeated sends');
 await db.query('UPDATE integration_commands SET next_attempt_at=now() WHERE id=$1',[throttledCmd.id]);
 await new IfoodIntegrationService(db,env,overridden({confirmOrder:async()=>{throw new IfoodHttpError(0);}})).processCommands();
 await service.processCommands();
 const uncertain=(await db.query('SELECT status,attempts FROM integration_commands WHERE id=$1',[throttledCmd.id])).rows[0];
 check(uncertain.status==='UNCERTAIN'&&uncertain.attempts===2,'Ambiguous mutations are not blindly resent');
 await db.query("UPDATE integration_connections SET delivery_dispatch_mode='BEFORE_READY_TIME',delivery_dispatch_minutes_before=15 WHERE id=$1",[integration]);
 await service.ingest(eventFor(manualRaw,'CFM','CONFIRMED'));await service.processEvents();await service.releaseDue();
 check((await call('GET',`/deliveries/${manualCreated.body.deliveryId}`)).body.status==='DRAFT','Scheduled search waits until the configured lead time');
 await db.query("UPDATE integration_connections SET delivery_dispatch_mode='MANUAL' WHERE id=$1",[integration]);await service.releaseDue();
 check((await call('GET',`/deliveries/${manualCreated.body.deliveryId}`)).body.status==='DRAFT','Manual mode never releases automatically');
 await db.query("UPDATE integration_connections SET delivery_dispatch_mode='BEFORE_READY_TIME',delivery_dispatch_minutes_before=120 WHERE id=$1",[integration]);await service.releaseDue();
 check((await call('GET',`/deliveries/${manualCreated.body.deliveryId}`)).body.status==='AWAITING_COURIER','Changing the lead time applies to pending orders');
 await db.query("UPDATE integration_connections SET delivery_dispatch_mode='IMMEDIATE' WHERE id=$1",[integration]);
 check((await db.query('SELECT status FROM integration_commands WHERE id=$1',[throttledCmd.id])).rows[0].status==='CONFIRMED','Authoritative event reconciles an uncertain command');
 await call('POST',`/external-orders/${manual.id}/actions`,{action:'CANCEL',cancellationCode:'501'});
 await service.ingest(eventFor(manualRaw,'CCR','CANCELLATION_REQUEST_FAILED'));await service.processEvents();
 check((await db.query("SELECT status,last_error FROM integration_commands WHERE external_order_id=$1 AND operation='CANCEL'",[manual.id])).rows[0].last_error==='IFOOD_CANCELLATION_REJECTED','Rejected cancellation does not close the delivery');
 check((await call('POST',`/deliveries/${manualCreated.body.deliveryId}/assign`,{courierId:driverId})).status===200,'Courier can be assigned to the new internal delivery');
 await db.query('UPDATE integration_connections SET auto_import_orders=false WHERE id=$1',[integration]);
 await service.ingest(eventFor(manualRaw,'CAN','CANCELLED'));await service.processEvents();
 check((await call('GET',`/deliveries/${manualCreated.body.deliveryId}`)).body.status==='CANCELLED','Known orders still receive cancellation when new imports are disabled');
 check((await db.query("SELECT 1 FROM outbox_events WHERE aggregate_id=$1 AND event_type='delivery.cancel'",[manualCreated.body.deliveryId])).rowCount===1,'Cancellation notification is queued for assigned courier and managers');
 await db.query('UPDATE integration_connections SET auto_import_orders=true,auto_create_delivery=true WHERE id=$1',[integration]);
 const batchRaw=[mockOrder('own',merchant),mockOrder('own',merchant)];
 for(const rawOrder of batchRaw){await service.ingest(eventFor(rawOrder));await service.ingest(eventFor(rawOrder,'CFM','CONFIRMED'));}
 await service.processEvents();await service.releaseDue();
 const batchOrders=(await db.query('SELECT id,delivery_id,external_order_id FROM external_orders WHERE external_order_id=ANY($1::uuid[]) ORDER BY external_order_id',[batchRaw.map(o=>o.id)])).rows;
 const route=await call('POST','/routes',{storeId:store,courierId:driverId,deliveryIds:batchOrders.map(o=>o.delivery_id),label:'Synthetic iFood batch'});
 assert.equal(route.status,201,JSON.stringify(route.body));checks++;
 const routeStops=route.body.stops as {id:string;stopType:string}[];
 for(const stop of routeStops.filter(s=>s.stopType==='PICKUP'))check((await call('POST',`/routes/${route.body.id}/stops/${stop.id}/complete`,{},courier)).status===200,'Batch pickup uses existing route flow');
 check((await db.query("SELECT 1 FROM integration_commands WHERE external_order_id=ANY($1::uuid[]) AND operation='DISPATCH'",[batchOrders.map(o=>o.id)])).rowCount===0,'Batch collection does not dispatch');
 check((await call('POST',`/routes/${route.body.id}/start`,{},courier)).status===200,'Batch route starts normally');
 await service.processCommands();await service.processCommands();await service.processEvents();
 check((await db.query("SELECT count(*)::int AS n FROM integration_commands WHERE external_order_id=ANY($1::uuid[]) AND operation='DISPATCH' AND attempts=1",[batchOrders.map(o=>o.id)])).rows[0].n===2,'One dispatch per external order on batch start, including NEXT_STOP');
 const next=(await db.query("SELECT id,external_order_id FROM deliveries WHERE route_id=$1 AND status='NEXT_STOP'",[route.body.id])).rows[0];
 const nextOrder=batchOrders.find(o=>o.id===next.external_order_id)!;
 await service.ingest(eventFor(batchRaw.find(o=>o.id===nextOrder.external_order_id)!,'CAN','CANCELLED'));await service.processEvents();
 check((await db.query('SELECT status FROM deliveries WHERE id=$1',[next.id])).rows[0].status==='CANCELLED','External cancellation closes the current route destination');
 check((await db.query("SELECT 1 FROM route_stops WHERE delivery_id=$1 AND stop_type='DELIVERY' AND status='SKIPPED'",[next.id])).rowCount===1,'Cancelled destination is skipped');
 check((await db.query("SELECT 1 FROM deliveries WHERE route_id=$1 AND status='NEXT_STOP'",[route.body.id])).rowCount===1,'Other batch destination advances without dispatch duplication');
 const webhookEnv={...env,NODE_ENV:'test' as const,IFOOD_EVENTS_MODE:'webhook' as const,IFOOD_WEBHOOK_ENABLED:true,IFOOD_WEBHOOK_SECRET:'synthetic-webhook-secret'};
 const webhookApp=await buildApp({env:webhookEnv,database:db});
 try{
   const rawBody=JSON.stringify(eventFor(mockOrder('own',merchant)));
   const signature=createHmac('sha256',webhookEnv.IFOOD_WEBHOOK_SECRET).update(rawBody).digest('hex');
   check((await webhookApp.inject({method:'POST',url:'/integrations/ifood/webhook',payload:rawBody,headers:{'content-type':'application/json','x-ifood-signature':'bad'}})).statusCode===401,'Webhook rejects an invalid signature');
   const delivered=await webhookApp.inject({method:'POST',url:'/integrations/ifood/webhook',payload:rawBody,headers:{'content-type':'application/json','x-ifood-signature':signature}});
   check(delivered.statusCode===202,'Webhook acknowledges only a persisted, signed event');
   check((await db.query('SELECT status FROM integration_events WHERE external_event_id=$1',[JSON.parse(rawBody).id])).rows[0].status==='RECEIVED','Webhook defers processing to the worker');
 }finally{await webhookApp.close();}
 const c=await call('PUT','/integrations/ifood/connection',{storeId:store,merchantId:merchant,enabled:false,autoImportOrders:true,autoCreateDelivery:true,deliveryDispatchMode:'MANUAL',deliveryDispatchMinutesBefore:15});check(c.status===200,'Connection can be disabled');
 check((await call('POST',`/external-orders/${id}/actions`,{action:'CANCEL',cancellationCode:'501'})).status===404,'Disabled integration prevents external commands');
 console.log(`OK: ${checks} iFood HTTP/PostgreSQL checks. Fixtures will be rolled back on exit.`);
 if(ui){await call('PUT','/integrations/ifood/connection',{storeId:store,merchantId:merchant,enabled:true,autoImportOrders:true,autoCreateDelivery:true,deliveryDispatchMode:'IMMEDIATE',deliveryDispatchMinutesBefore:15});
   console.log(JSON.stringify({temporaryUi:true,email:prefix+'-manager@example.test',password,merchant}));const timer=setInterval(()=>void(async()=>{await db.query('UPDATE integration_connections SET last_worker_at=now() WHERE id=$1',[integration]);await service.processEvents();await service.releaseDue();await service.processCommands();})().catch(()=>{}),5000);
   await new Promise<void>(resolve=>{process.once('SIGINT',resolve);process.once('SIGTERM',resolve);});clearInterval(timer);}
}finally{await app?.close();await connection.query('ROLLBACK');connection.release();await pool.end();}
